### ISSUE TITLE
github action build 시 발생하는 오류

### ISSUE THREAD

**Issue by Bumkeyy** [typescript-kr/typescript-kr.github.io#128]
* 내용: github action release시 오류 발생

```shell
Run version="$(date +%Y-%m-%d-%S)"

> typescript-study.github.io@1.0.0 build:gitbook /home/runner/work/typescript-kr.github.io/typescript-kr.github.io
> npx gitbook build

Installing GitBook 3.2.3
/home/runner/work/typescript-kr.github.io/typescript-kr.github.io/node_modules/npm/node_modules/graceful-fs/polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at /home/runner/work/typescript-kr.github.io/typescript-kr.github.io/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:169:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-study.github.io@1.0.0 build:gitbook: `npx gitbook build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-study.github.io@1.0.0 build:gitbook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-07-28T11_07_51_551Z-debug.log
##[error]Process completed with exit code 1.
```

**Comment by samsara-ku** [comment]
아마도 도움이 될 것 같아서 문서 하나 들고왔습니다.

https://github.com/GitbookIO/gitbook-cli/issues/68

저도 한 번 테스트를 해봤는데, latest node(v14.7.0)에 gitbook-cli(v2.3.0), 그리고 Gitbook(v3.2.3)으로도 돌아가더군요.

중간에 `rm -rvf ~/.gitbook`과 같은 커맨드로 gitbook directory를 지우던데, 이것만 문제가 아니라면 괜찮지 않을까요?

확인 부탁드립니다~

@Bumkeyy

**Comment by yeonjuan** [comment]
github 액션에서 node 버전을 특정 버전을 사용하도록 설정했습니다.
